// Generated by CoffeeScript 1.9.3
(function() {
  var app, child_process, dns, express;

  dns = require('dns');

  child_process = require('child_process');

  express = require('express');

  app = express();

  app.set('view engine', 'hjs');

  app.get(/([a-z])(\d+)(-[-\w]*)?(\..+)?/, function(req, res) {
    var domain, port;
    console.log(req.params);
    domain = req.params[0] + '.lv5.ac';
    port = parseInt(req.params[1]);
    return dns.resolve(req.params[0] + '.lv5.ac', function(err, address, family) {
      var params, template;
      if (err) {
        return res.status(500).send(err);
      }
      if (req.params[2]) {
        params = req.params[2].split('-');
      }
      console.log(req.params[3]);
      switch (req.params[3]) {
        case '.smartproxy':
          return res.render('smartproxy', {
            proxy: address + ':' + req.params[1]
          });
        case '.mobileconfig':
          if (params[params.length - 1] === 'legacy') {
            template = 'ios-legacy';
          } else {
            template = 'ios';
          }
          return app.render(template, function(err, mobileconfig) {
            return child_process.execFile('openssl', ['smime', '-sign', '-signer', '/etc/nginx/railgun.ac.crt', '-inkey', '/etc/nginx/railgun.ac.key', '-certfile', '/etc/nginx/intermediate_domain_ca.crt', '-nodetach', '-outform', 'der'], function(error, stdout, stderr) {
              if (err) {
                return res.status(500).send(err);
              }
              if (stderr.length > 0) {
                return res.status(500).send(stderr);
              }
              res.type('application/x-apple-aspen-config');
              return res.send(stdout);
            });
          });
        default:
          res.type('application/x-ns-proxy-autoconfig');
          return res.render('proxy', {
            https_proxy: domain + ":" + (port + 1),
            http_proxy: address + ":" + port
          });
      }
    });
  });

  app.listen(3000);

}).call(this);

//# sourceMappingURL=app.js.map
